<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>KitchenCore</AssemblyName>
    <RootNamespace>KitchenCore.Desktop</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Photino.NET" Version="4.0.16" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>

</Project>
